const TOURNAMENT_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  GROUP_STAGE: 'GROUP_STAGE',
  KNOCKOUT: 'KNOCKOUT',
  FINISHED: 'FINISHED',
};

const MATCH_STATUS = {
  SCHEDULED: 'SCHEDULED',
  FINISHED: 'FINISHED',
};

const MATCH_ROUND = {
  GROUP: 'GROUP',
  R16: 'R16',
  QUARTER: 'QUARTER',
  SEMI: 'SEMI',
  THIRD: 'THIRD',
  FINAL: 'FINAL',
};

const POINTS = {
  WIN: 3,
  DRAW: 1,
  LOSE: 0,
};

const MIN_GROUPS = 4;
const MAX_GROUPS = 12;

module.exports = {
  TOURNAMENT_STATUS,
  MATCH_STATUS,
  MATCH_ROUND,
  POINTS,
  MIN_GROUPS,
  MAX_GROUPS,
};
